apiVersion: apps/v1
kind: Deployment
metadata:
  name: Timeshit
  labels:
    app: Timeshit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Timeshit
  template:
    metadata:
      labels:
        app: Timeshit
    spec:
      containers:
      - name: Timeshit
        image: ouma197:laster  # Remplace par le nom correct de ton image
        ports:
        - containerPort: 8082  # Mets ici le port sur lequel ton application Station Ski Ã©coute
