apiVersion: v1
kind: Service
metadata:
  name: Timeshit
spec:
  type: NodePort
  selector:
    app: Timeshit   # Doit correspondre au label de ton Deployment
  ports:
    - protocol: TCP
      port: 8080           # Port interne du service (celui utilisé par ton app)
      targetPort: 8080     # Port sur lequel ton container écoute
      nodePort: 30001      # Port exposé sur le nœud Kubernetes (entre 30000 et 32767)
